[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate deploy",
  "npm run build"
]

[start]
cmd = "npm start"
